### ISSUE TITLE
Command `checkly groups` has unformatted, unsorted output

### ISSUE THREAD

**Issue by tnolet** [checkly/checkly-cli#136]
This is a `checkly groups` command on our Production E2E account.

![image](https://user-images.githubusercontent.com/3802923/146838537-17be433f-923c-407b-aa1c-24a71e3a0cff.png)

**Comment by umutuzgur** [comment]
@tnolet this is due to having a lot of locations. How would you like the solution to look, locations truncated after a certain length? We are all familiar with this problem from sql outputs I believe

**Comment by brampling** [comment]
Is there a better text table formatter that can keep these results in columns but multi-line?

**Comment by ianaya89** [comment]
We have the "plain" output type that should work ok with things like this but we still need to find a way to fix this in "human" which is the default. Maybe truncating data?

If the check has all locations we can simply show something like "all" but of course will not be a solution for all cases

**Comment by tnolet** [comment]
@umutuzgur @brampling @ianaya89 I would like the output to be readable. I do not have a preferred solution, but many times something like `us-east-1, eu-west-1 + 9 others` works.
