### ISSUE TITLE
Command `checkly projects` returns a project called `checkly-cli`

### ISSUE THREAD

**Issue by tnolet** [checkly/checkly-cli#140]
On a fresh repo, I run `checkly project` and get back some data in the `checkly-cli` project. I don't know what that means.

```
checkly projects


id  name         repoUrl                                 activated  muted  state            accountId  created_at                updated_at
--  -----------  --------------------------------------  ---------  -----  ---------------  ---------  ------------------------  ----------
93  checkly-cli  git@github.com:checkly/checkly-cli.git  true       false  [object Object]             2021-12-15T17:23:32.375Z  null  
```

**Comment by ianaya89** [comment]
This seems like an expected output, someone created/deployed a checkly project inside the `checkly-cli` repo.  The values `name` and `repoUrl` were filled from the file-system and git repo.

We can discuss which is the data we should show when listing the existing projects

**Comment by umutuzgur** [comment]
@tnolet @ianaya89 I will drop some data in the projects table. We have things we don't use so they shouldn't be there at the beginning

**Comment by tnolet** [comment]
@umutuzgur @ianaya89  so what will a user see, how does this work? The line has an `[object Object]` and an empty `accountId`. It's very confusing. Either the data is correct or we remove the whole command.

this is not a biggy for MVP though

**Comment by umutuzgur** [comment]
I will drop state, account and the other unused stuff. We should also reconsider putting a user's local path in there
