### ISSUE TITLE
`login` with Github redirects to error page

### ISSUE THREAD

**Issue by tomerlichtash** [checkly/checkly-cli#232]
Is it possible to login to CLI and auth via Github?
According to the docs it is, however – running `checkly` yields following error message:

```
$ checkly

 ERROR  Invalid Session

ℹ Run checkly login or manually set CHECKLY_API_KEY & CHECKLY_ACCOUNT_ID environment variables to setup authentication.
```
I followed the above like so:

1. Run `checkly login` in CLI to auth with Checkly.
2. Get an auth URL and follow it to the browser.
3. Get Checkly's Login page, and click "Sign in with Github"
4. Get redirected to an error page with the Title "Oops!, something went wrong"

* Expected result: Login successful.
* Actual result: Redirect to error page with no errors in console.

**Comment by ianaya89** [comment]
Hi @tomerlichtash, thanks for reporting. The development of the CLI was put on hold while we focus on other Monitoring as Code solutions and we re-think the strategy we are going to take.

In the meantime, I can recommend you test our existing solutions:
- [Terraform Provider](https://github.com/checkly/terraform-provider-checkly)
- [Pulumi Provider](https://github.com/checkly/pulumi-chekly)

If there is something else I can do for you, do not hesitate to reach me at nacho[at]checklyhq.com

Thanks!
