### ISSUE TITLE
Add support for all features in `constructs`

### ISSUE THREAD

**Issue by clample** [checkly/checkly-cli#328]
We should polish up the `constructs` to make sure that all key features are supported.

Alert Channels:
* [x] OpsGenie
* [x] Pagerduty
* [x] Webhook

API Checks:
* [x] setup & teardown scripts
* [x] Body
* [x] Headers
* [x] Query params
* [x] Authentication
* [x] Response time limits

Groups:

* [x] setup & teardown scripts

Browser check:
* [x] Currently `code.entrypoint` needs to be an absolute path. Let's also add support for relative paths?

Misc:
* [x] Rather than needing to assign values for every option (`activated`, `muted`, etc.) there should be sensible defaults

**Comment by gespi-consensys** [comment]
can we support descriptions on the OpsGenie integration? [The opsgenie api supports this ](https://docs.opsgenie.com/docs/alert-api). Would be great to be able to provide our SRE/Incident responders with additional information on an opsgenie alert like where to find a runbook for a certain url.

**Comment by tnolet** [comment]
@gespi-consensys thanks for contributing. I think we have a more general feature request for that here https://github.com/checkly/public-roadmap/issues/256

Could you also upvote this? If / when we ship this we would also want to make this available in the UI of course.

**Comment by gespi-consensys** [comment]
ty thumbs up'd
