### ISSUE TITLE
Engineering release requirements

### ISSUE THREAD

**Issue by umutuzgur** [checkly/checkly-cli#395]
We have a few things to get the repo ready for a GA release. This ticket holds the necessary things to call it ready

Check list:
- [x] Show out of credit error like a test result failure and not just a console.error
- [x] Remove console.* from everywhere in the code base except for commands and add an eslint rule
- [x] Cleanup project schemas for resources, remove `stripUnknown` from them to get `400` immediately

**Comment by clample** [comment]
@umutuzgur I'm taking an initial look at the out-of-credit error handling.

We'll already mark the check as failed when the account is out of credit: https://github.com/checkly/checkly-cli/blob/afe1483e9dc6f6d530973301705a6fc547969abb/package/src/services/check-runner.ts#L80-L88

I'll mark this as done.

For the TODO in the code - "Find a way to abort. The latest version supports this but doesn't work with TS " - is there anything to do there? It seems like it was added back when the code was structured differently - I'm not sure if this is still relevant.
