### ISSUE TITLE
How to use playwright config

### ISSUE THREAD

**Issue by alvarlagerlof** [checkly/checkly-cli#407]
I have some settings in my playwright config (mainly different screen sizes). How do I use then when running `checkly test`?

**Comment by tnolet** [comment]
@alvarlagerlof right now, we do not parse the `playwright.config.js` file. I would recommend creating a separate file for defaults you want to use with Checkly. We are looking into how / if we want to support that, but there are some snags.

**Comment by tnolet** [comment]
An example in this repo is here https://github.com/checkly/checkly-cli/blob/main/examples/simple-project/src/defaults.js

**Comment by alvarlagerlof** [comment]
It's not just default though, I don't want to have to redefine tests for many screen sizes. The config runs things at all of the configured ones. Is there a good alternative to that?

**Comment by tnolet** [comment]
@alvarlagerlof at this point, a simple loop will also work, where you export the screen sizes and loop over the array. We will look at how we can support this natively.
