### ISSUE TITLE
checkly whoami doesn't show user info

### ISSUE THREAD

**Issue by umutuzgur** [checkly/checkly-cli#425]
The command just prints account name and account id but nothing related to the user. The description of this command also indicates user related info

**Comment by nahuelon** [comment]
@umutuzgur @tnolet , I completed the `/next/users/me` endpoint in the Public API. At the moment, it returns the user's `id`, `name`, `nickname` and `email`. Let me know which other fields you want to add in the `npx checly whoami` response. FYI, the object has information about the `settings`, `membership` and all the `account` and `plan` information).

**Comment by tnolet** [comment]
Let's keep it right. Only name and nickname are needed. No need to potentially expose an email.
