### ISSUE TITLE
Color cli output

### ISSUE THREAD

**Issue by alvarlagerlof** [checkly/checkly-cli#427]
It would be nice to have some colors in the cli output too read things more easily.

**Comment by tnolet** [comment]
@alvarlagerlof Any specifics your are looking for? We have color output already and follow what you would get in Jest and Playwright.

**Comment by alvarlagerlof** [comment]
Ah, then I guess I've set something up wrong when running in GitHub actions. It's all grey there.

**Comment by tnolet** [comment]
We are suppressing coloring I think in CI as it can get very wonky. Let us have a look if we can tweak that.
