### ISSUE TITLE
RFC: Create init command to create a checkly.config.js

### ISSUE THREAD

**Issue by umutuzgur** [checkly/checkly-cli#433]
We have some defaults in the checkly.config.js. These are hard to disable and needs some hacking to get this done. Therefore, we propose an init command to help users create the configs automatically. This will be quite similar to the npm init command

**Comment by tnolet** [comment]
Key items we can help users with are:
- choosing the file type: JS/TS. i.e. `Do you want to use Typescript? Y/n`
- choosing if they want to setup default `checkly.config.js` in the root. `Do you want to generate a default checkly.config.js. Y/n`
- choosing if they want to create a set of examples: api check, browser check, one alert channel. `Do you want to generate a set of examples. Y/n`

This flow should be triggerable also via `npx create @checkly/cli`.
