### ISSUE TITLE
Checks created through CLI have "null" environmentVariables value

### ISSUE THREAD

**Issue by adamwardecki** [checkly/checkly-cli#442]
Version: `@checkly/cli/0.3.9 darwin-x64 node-v16.17.0`

Issue: 

When creating a check through CLI the `environmentVariables` property will have a `null` value by default. This is different from the Webapp where the default is `[]`. 

To reproduce: 

1. Create a basic check from the getting started section of https://www.npmjs.com/package/@checkly/cli
2. Run `npx checkly deploy`
3. Go to the web app and check the response from `/checks` endpoint in the network tab - env vars array is `null`

**Comment by tnolet** [comment]
@clample can you look at this?

**Comment by umutuzgur** [comment]
@nahuelon just pinging you in case you didn't get a notification for the assignment
