### ISSUE TITLE
`--help` flag doesn't work for subcommands

### ISSUE THREAD

**Issue by clample** [checkly/checkly-cli#448]
Running `npx checkly test --help` (or `--help` for any other command) gives the following:
```
$ npx checkly test --help
Test checks on Checkly

    TypeError: (cmd.args || []).filter is not a function
```

We should fix `--help` so that it describes all of the relevant command line flags.

**Comment by umutuzgur** [comment]
Weird, this only happens with the released version

**Comment by umutuzgur** [comment]
It is related to `oclif.manifest.json` weirdly
