### ISSUE TITLE
User login

### ISSUE THREAD

**Issue by ianaya89** [checkly/checkly-cli#46]
# Rationale
We want to explore a user based login routine, similar to how the Heroku and Vercel toolchain/cli work. This enabled the following:
- Stricter control for our customers. When a user leaves the organisation, the loose their access. The alternative is that organisations needs to cycle their API tokens.
- User based login enabled users to switch between multiple Checkly accounts they might have.

# Acceptance criteria

- [ ] A user executes `checkly login` and is presented with a link to open in their browser.
- [ ] On navigating to the link, the user can log in to Checkly.
- [ ] After successful login, we show a screen that a user can close the browser. 
- [ ] The CLI confirms the successful authentication.
- [ ] Any authentication errors are handled gracefully with a friendly error message (either in browser or in the CLI) that the authentication failed.

# Implementation
We will most likely have to create a separate and distinct auth scheme for this feature. There are multiple options here.
Solutions like Stripe and Vercel automatically create a dedicated token for the CLI, which is listed in the account profile.

**Stripe** generates this after going thru the `stripe login`-flow on the command line
![image](https://user-images.githubusercontent.com/3802923/133599698-eae10d73-4a71-41c6-bbe6-7877d3024808.png)

**Vercel** does something very similar. On `vercel login` a dedicated token is created.

![image](https://user-images.githubusercontent.com/3802923/133599555-a05258d5-6722-4f09-91b4-c10d947d03e8.png)

**Comment by ndom91** [comment]
We currently only have account-wide API tokens, we'll have to see what we need to do backend-wise to generate tokens on a user level for this (and future) use cases.

**Comment by ianaya89** [comment]
This will also require changes in the way we do authentication in the Public API. We could probably end with a mixed system that allows API KEYS or Token to perform auth.
