### ISSUE TITLE
add `optional` and `default` values to some properties

### ISSUE THREAD

**Issue by tnolet** [checkly/checkly-cli#472]
The following properties can easily be given defaults and should be marked optional in the types

# ApiCheck

https://github.com/checkly/checkly-cli/blob/5a18ea807be9aeb9000cf7b803c5ecc56be3269c/packages/cli/src/constructs/api-check.ts#L81

- `degradedResponseTime: 5`
- `maxResponseTime: 20`
-  `followRedirects`: true,
-  `skipSsl`: false,
-  `assertions`: []

```
export class ApiCheck extends Check {
  request: Request
  localSetupScript?: string
  localTearDownScript?: string
  degradedResponseTime: number
  maxResponseTime: number
```

# AlertChannelProps

https://github.com/checkly/checkly-cli/blob/5a18ea807be9aeb9000cf7b803c5ecc56be3269c/packages/cli/src/constructs/alert-channel.ts#L3

I think all the props here can have sane defaults and should be optional:

- `sendRecovery: true`
- `sendFailure: true`
- `sendDegraded: true`
- `sslExpiry: true`
- `sslExpiryThreshold: 30`

```
export interface AlertChannelProps {
  /**
   * Determines if an alert should be send for check recoveries.
   */
  sendRecovery: boolean
  /**
   * Determines if an alert should be send for check failures.
   */
  sendFailure: boolean
  /**
   * Determines if an alert should be send when a check is degraded.
   */
  sendDegraded: boolean
  /**
   * Determines if an alert should be send for expiring SSL certificates.
   */
  sslExpiry: boolean
  /**
   * At what moment in time to start alerting on SSL certificates.
   */
  sslExpiryThreshold: number
```

# CheckGroup

https://github.com/checkly/checkly-cli/blob/5a18ea807be9aeb9000cf7b803c5ecc56be3269c/packages/cli/src/constructs/check-group.ts#L30

these should be optional like they are for the `Check` interface

 - `activated`: true,
-  `muted`: false,
-  `runtimeId`: account default,
-  `tags`: []
-   `environmentVariables`: [],
-  `apiCheckDefaults`: {},
-  `browserCheckDefaults`: {},

**Comment by clample** [comment]
For the implementation, I think that we should try to put these in Joi defaults in the backend.

We could also add defaults in the checkly-cli, but I think that having the defaults in the backend gives us more flexibility for updating things later on.

**Comment by tnolet** [comment]
@clample yes, that is fine. TS should just not start blaring that it wants this all defined up front.

**Comment by clample** [comment]
We have some already defaults in place via the public API that are different than those proposed above. I think that it could be nice to keep the same defaults across all the public API + TF + MaC. On the other hand, maybe these new defaults are better and we shouldn't let the public API and TF hold us back from using these in MaC.

Checks:
* `degradedResponseTime`: 10000
* `maxResponseTime`: 20000

Alert Channels:
* `sslExpiry`: false

**Comment by tnolet** [comment]
@clample agreed

**Comment by clample** [comment]
I've updated it so we're using the defaults from the backend now. I just need to document them in the README, then I can close this.

**Comment by tnolet** [comment]
@clample what actions do we need to take here docs wise?

**Comment by clample** [comment]
@tnolet I think that we should document somewhere what the defaults are. Do you think that this fits OK in the website docs that you're creating right now? I can go in and add them there once you've merged the initial draft.

**Comment by tnolet** [comment]
> @tnolet I think that we should document somewhere what the defaults are. Do you think that this fits OK in the website docs that you're creating right now? I could go in and add them there once you've merged the initial draft.

yes, they should be marked as such. Maybe a simple MD table structure should work there

**Comment by tnolet** [comment]
@clample we can move ahead with this without updating the docs for now.

**Comment by clample** [comment]
@tnolet if we don't care about documenting the default values, then I think that this ticket is all set for now.

**Comment by umutuzgur** [comment]
@tnolet Chris and I just talked about moving the defaults to the CLI to avoid unwanted api default changes for the users. We can also do this along with the beta state but I leave it to you

**Comment by tnolet** [comment]
Closing this ticket for now as it seems to not be an issue for feature rollout
