### ISSUE TITLE
Account Switching 

### ISSUE THREAD

**Issue by ianaya89** [checkly/checkly-cli#48]
# Rationale

A single, authenticated user can have multiple accounts on Checkly. We want to give users the option to explicitly switch between accounts from the CLI.

This switching makes sense for many interactive, read-only commands like `checkly status` where a user might want to quickly see what's up in their accounts.

The switching might cause friction when 
1. A user is on an initialized project that is deployed.
2. Then switches to a different account.
3. Then runs deploy again. This would create a completely new project and set of checks on the API/cloud side.

At this moment, this is acceptable and actually expected behaviour.

# Acceptance criteria

We do not have to reinvent the wheel here. The functionality should be similar to for instance the `vercel teams` command.

- [x] `checkly accounts` should list the accounts you have access to. This is an alias for `checkly accounts ls`
- [x] `checkly accounts switch`should start an interactive prompt that allows the user to pick an account.
- [ ] If a user has only one account, the user cannot switch.

Example for account switcher from the `vercel` cli.

```
vercel teams switch
> Switch to: (Use arrow keys)
  ── Personal Account ──────────
❯ Tim Nolet (timnolet) (current) 
  ── Teams ─────────────────────
  Checkly (checkly) 
  ──────────────────────────────
  Abort 
```

**Comment by ndom91** [comment]
We currently store the active token in the global config (under `~/.config/@checkly...`), right, so theres no per-project switching. However, I think the authentication / token storage should probably stay at the global level, but then potentially with different "profiles" one can switch between (like how they do it in `~/.aws/config`, for example). What're you're thoughts?

**Comment by tnolet** [comment]
> We currently store the active token in the global config (under `~/.config/@checkly...`), right, so theres no per-project switching. However, I think the authentication / token storage should probably stay at the global level, but then potentially with different "profiles" one can switch between (like how they do it in `~/.aws/config`, for example). What're you're thoughts?

@ndom91 I just discussed this with @ianaya89. Short version is that the token will not supply account information. The API will give a list of accounts the user has access to, similar to our web-app facing API. What we need to do — and @ianaya89 correct me here — is we store the `currentAccountId` in the `config.json` and send it along with each API request in the `X-Checkly-Account` header.

**Comment by ianaya89** [comment]
That is correct!
@ndom91 we can set a call tomorrow to review this and estimate the effort.

**Comment by ianaya89** [comment]
I made some changes in our Public API to address this feature. 
Some of those changes will need a refactor once we migrate API Keys and make them user scoped

- Make /accounts endpoint return all user accounts
- Add /accounts/me endpoint which return current user account

> [Shortcut ticket](https://app.shortcut.com/checkly/story/4706/add-public-api-endpoint-to-return-all-user-accounts)
