### ISSUE TITLE
story: Restrict logical id to alphanumeric with special characters [a-zA-Z0-9_-/#]

### ISSUE THREAD

**Issue by umutuzgur** [checkly/checkly-cli#487]
### Story description

We want to help our users avoid using ids prone to making mistakes, like empty spaces or tabs. I suggest using `[a-zA-Z0-9_-/#]` or simply `[\w-/#]` to make sure they have a simpler but still extensive logical ids combination. This should be a FE and a BE restriction

**Comment by nahuelon** [comment]
@umutuzgur , maybe we can restrict the `_` char too. In the future we could have short-URL or project specific URL like `<projectId>.test.checklyhq.com` or `<projectId>.checkly-tests.com` to access the test sessions.

**Comment by nahuelon** [comment]
@umutuzgur , I had to add the `.` character since some `logicalId` are file paths, i.e.:

![image](https://user-images.githubusercontent.com/5315705/217634513-8f1c8203-8987-47bc-a635-9a0b402f81f1.png)

**Comment by nahuelon** [comment]
@umutuzgur , I added the `backend` validation within the project schema  https://github.com/checkly/checkly-backend/pull/3873
