### ISSUE TITLE
Remove conf command and re-organize confi properties

### ISSUE THREAD

**Issue by ianaya89** [checkly/checkly-cli#50]
## Rationale

The current config method adds too much machine/environment specific globals to the mix. This creates unexpected and hard to debug situations. I can only see two very specific global vars that make sense to keep.

- Auth token after user login: prepending / appending a token on each call would be terrible.
- Selected account: after switching an account, I expect my CLI to target that account exclusively.

Any and all other options should be scrapped.

## Acceptance criteria

- [ ] After login, a user can use the CLI based on that login credentials without any extra parameters or specific commands.
- [ ] After switching to a different account, a users CLI interactions target that specific account only.

**Comment by ndom91** [comment]
For this one, I just want to emphasize we don't necessarily need to completely tear it out and replace it. But lets just make sure its super straight forward and easy to use for the users :+1:

**Comment by ianaya89** [comment]
The current config method mostly fits the acceptance criteria. There are now extra steps to do with config after running the login command. 

Right now there are only 2 env variables (NODE_ENV and API_KEY). 

I will review this behaviour to make it more natural, remove some stuff and add support for accounts/profiles

**Comment by ianaya89** [comment]
The config file is stored in the user preferences directory:

```
macOS: ~/Library/Preferences/@checkly/cli-nodejs
Windows: %APPDATA%\MyApp-nodejs\Config (for example, C:\Users\USERNAME\AppData\Roaming\@checkly/cli-nodejs\Config)
Linux: ~/.config/MyApp-nodejs (or $XDG_CONFIG_HOME/@checkly/cli-nodejs)
```
