### ISSUE TITLE
E2E Integration Testing

### ISSUE THREAD

**Issue by ianaya89** [checkly/checkly-cli#51]
Ensure theres a robust E2E integration test of _at least_ the deploy + test cmd with the prod backend - ndo @ 02.12.21

**Comment by ndom91** [comment]
Theres already some jest tests for this in the backend repo in the `../public-api/projects` directory for testing the sync outcome in terms of the api actions and response. Maybe it makes sense to use the same fixtures / mocked api data both there and for any potential sync tests on this side of the equation. That way we know they're both handling the same inputs correctly.
