### ISSUE TITLE
story: Improve the CI/CD flow of the cli

### ISSUE THREAD

**Issue by umutuzgur** [checkly/checkly-cli#516]
### Story description
We want to improve the CI/CD workflow of the cli. This involves lint checks, easier releases and auto release message creation using conventional commits.

We can use eslint with simple git-hooks for lint checks. Package versioning and release messages can be achieved with sematic-release. If there is anything better, I'm also open to suggestions

- [x] Linter, local and CI - https://github.com/checkly/checkly-cli/pull/731
- [x] Automatic package versioning upon github releases - https://github.com/checkly/checkly-cli/pull/769
- [x] Automatic release message creation - https://github.com/checkly/checkly-cli/pull/769

**Comment by nahuelon** [comment]
> Just my two cents fro the local lint - I think that having a lint in CI is enough to keep `main` tidy. I like to regularly commit in-progress work, and I wonder if a git lint hook will block that.
> 
> Maybe there's a way to disable the local linting, though.

@clample , if I understood right, you want to commit changes that don't respect lint rules. In that case, you can use `git commit --no-verify` where the `--no-verify` flag tells `simple-git-hooks` to bypass all the checks. For example:

![image](https://github.com/checkly/checkly-cli/assets/5315705/8fb34e35-c17b-4b51-9832-e87fe3c8aaf5)

**Comment by clample** [comment]
Thanks @nahuelon for the workaround 👍
