### ISSUE TITLE
bug: adding alert channels to check in the config doesn't work

### ISSUE THREAD

**Issue by chocolateofpain** [checkly/checkly-cli#519]
### Node.js version

v16.17.0

### NPM version

8.15.0

### @checkly/cli version

@checkly/cli/0.3.14 darwin-arm64 node-v16.17.0

### Steps to reproduce

1. add alert channels in the checkly config like in the example in the docs: https://www.checklyhq.com/docs/cli/project-structure/#global-configuration
2. deploy
3. check in the account: the alert channels are not added to the individual checks.

### What is expected?

Alert channels are added to all the checks.

### What is actually happening?

Alert channels are not added to the checks. Sadge.

**Comment by clample** [comment]
It looks like this was caused since there was both a `checkly.config.js` and `checkly.config.ts` - one with the default alert channels and one without.

Adding the default alert channels seems to be working fine, so I'll go ahead and close this.
