### ISSUE TITLE
feat: Allow Checkly to Export Test Results to playwright Native html Report

### ISSUE THREAD

**Issue by fonzi** [checkly/checkly-cli#523]
### What problem does this feature solve?

Ideally, have a way to export the native playwright test results as HTML. This would allow clients to use those results however they need. 

At my current company, we are looking at switching from TestRails to TestOps as our main test case manager. We can use this [plugin](https://www.npmjs.com/package/allure-playwright) to generate allure reports. Letting us upload it to TestOps and have automated test case management. 

Our case is that it'd be ideal for managers / SOC2 Auditors to get all the tests we have in one centralized location (TestOps) instead of having to also give them access to the checkly internal dashboard. 

Playwright does support an HTML report as it's the native tool. However, it also showcases some [third-party reporters ](https://playwright.dev/docs/test-reporters#third-party-reporter-showcase)

This feature would essentially emulate `npx playwright test --reporter=${report_tool}`
Ideally, the tests that we are thinking of running from checkly would not be part of our normal smoke/regression runs since they are always running. So having them integrate into TestOps would be ideal here.  And maintain trends in a single place. 

This is still in the brainstorming phase so we have no immediate need to solve this. 

### How would you implement this feature?

It would be great to add a button at the app.checklyhq.com board with an option to export all the last runs and export that as an HTML report. Or even from the edit screen where I can export the results as a native playwright report.

**Comment by umutuzgur** [comment]
@tnolet just pinging in case this got out of your radar

**Comment by tnolet** [comment]
@fonzi and me chatted on Slack about this. This would be a good addition, although my gut says JUNIT is a more widely and better supported format

**Comment by fonzi** [comment]
@tnolet I agree from a market share JUnit might be the most popular here. I'd be good with just a JUnit report since then I could convert that into almost any other report type. And playwright does support JUnit as one of its reporters 

https://playwright.dev/docs/test-reporters#junit-reporter

I'd have to look, but I'm pretty sure that would solve my use case since I could just import JUnit to Allure TestOps.

**Comment by tnolet** [comment]
@fonzi we are tracking this here https://github.com/checkly/checkly-cli/issues/554

**Comment by fonzi** [comment]
Thank you @tnolet!

**Comment by tnolet** [comment]
Closing this in favour of https://github.com/checkly/checkly-cli/issues/554
