### ISSUE TITLE
feat: polish output from `npx checkly deploy --preview`

### ISSUE THREAD

**Issue by clample** [checkly/checkly-cli#526]
### What problem does this feature solve?

The current output for `npx checkly deploy --preview` is just the raw response from the backend:
```
$ npx checkly deploy --preview
{
  diff: {
    checks: {
      'public-resource_/public-stats': 'UPDATE',
      'public-resource_/v1/runtimes': 'UPDATE',
      '__checks__/homepage.spec.ts': 'UPDATE'
    }
  }
}
```

This is clear enough and users will likely understand it, but it's not consistent with the human readable output used in the rest of the CLI. We should consider printing this with different formatting and maybe use colored output (red for deletion, green for creation, etc). I'm not sure what exactly the best format would be, but maybe something like:

```
Deleting the following resources:
   (Check) 'My Browser Check'
   (Check Group) 'Production Check Group'
   
Creating the following resources:
    (Check) 'New Browser Check' my-project/__checks__/new.check.ts
```

**Comment by ndom91** [comment]
Here's some potential inspiration for this:

- [cdk-pretty-diff](https://github.com/joshweir/cdk-pretty-diff)
- [prettyplan](https://github.com/chrislewisdev/prettyplan) (for TF)
