### ISSUE TITLE
docs: clarify logical ID's and `testMatch` checks

### ISSUE THREAD

**Issue by clample** [checkly/checkly-cli#528]
### What is the improvement or update you wish to see?

For Browser Checks automatically created from `*.spec.ts` files with `testMatch`, the logical ID is automatically generated and is based on the path of the check. One important limitation of this is that moving a `*.spec.ts` file can cause the check deleted then recreated when running `npx checkly deploy`, rather than simply updating the check. This can cause users to loose the history of the check.

This is a potential footgun that might be worth a small call-out in the docs. For users that which to avoid this, they may be better off creating checks directly using the `BrowserCheck` construct to have more control over the logical ID.
 

### Is there any context that might help us understand?

no additional context

**Comment by chocolateofpain** [comment]
Additional information: recreating a check not only happens when a check is moved but also when it's simply added to a group (provided the check was created using `testMatch`.

**Comment by clample** [comment]
This is documented now (["Using checkMatch and testMatch"](https://www.checklyhq.com/docs/cli/using-check-test-match/)). I'll close this issue.

> When you rename a file that was previously deployed, the logicalId will change. The effect is that once you deploy again the new logicalId will trigger a deletion of the “old” Check and a creation of this “new” Check and you will lose any historical metrics.
