### ISSUE TITLE
bug: regex for header is not persisted using AssertionBuilder

### ISSUE THREAD

**Issue by tnolet** [checkly/checkly-cli#534]
### Node.js version

18.12.1

### NPM version

8.19.2

### @checkly/cli version

0.4.0

### Steps to reproduce

Create an assertion as follows using the `AssertionBuilder`

```
AssertionBuilder.headers('strict-transport-security', 'max-age=(\\d+)').greaterThan(10000),
```

### What is expected?

the regex is persisted on deploy and it looks like this in the UI

![CleanShot 2023-02-16 at 14 37 58](https://user-images.githubusercontent.com/3802923/219379815-eb718e04-c14f-4d3f-ae95-9c6a58cc2be3.png)

### What is actually happening?

the regex is not persisted.

**Comment by nahuelon** [comment]
I added the missing `regex` property to the `assertions` schema in the backend: https://github.com/checkly/checkly-backend/pull/3901
