### ISSUE TITLE
bug: the `doubleCheck` property is not available on a `CheckGroup`

### ISSUE THREAD

**Issue by tnolet** [checkly/checkly-cli#536]
### Node.js version

18

### NPM version

8

### @checkly/cli version

0.4.0

### Steps to reproduce

- Create a `CheckGroup` and try assigning a `doubleCheck` property.
- Or, set a `doubleCheck` default in `checkly.config.ts`. The value will not be inherited by any `CheckGroup` in the project. 

### What is expected?

The `doubleCheck` property is available on any `CheckGroup` and inherits just like Checks do.

### What is actually happening?

The setting is ignored

**Comment by umutuzgur** [comment]
@tnolet I'm gonna close this because I can't repro this

**Comment by tnolet** [comment]
The `CheckGroup` has no doubleCheck property https://github.com/checkly/checkly-cli/blob/main/packages/cli/src/constructs/check-group.ts

whereas the UI and API spec / version does have it.
