### ISSUE TITLE
bug: __checkFilePath points to the wrong path when checkly resources are imported from different files

### ISSUE THREAD

**Issue by umutuzgur** [checkly/checkly-cli#549]
### Node.js version

16

### NPM version

8

### @checkly/cli version

0.4.3

### Steps to reproduce

Let's say you have your checkly resources in file called `resources.js|ts` and these are imported by a check file, group.check.js, the relative path entrypoint calculation will be wrong in this case. `__checkFilePath` will be set as `group.check.js` and the `entrypoint` relative path functionality will break

### What is expected?

That we have a relative path built according to the file which created the resources

### What is actually happening?

Explained in the steps to reproduce

**Comment by clample** [comment]
I've updated the docs to clarify this a bit, but it's still a tricky aspect of the CLI. Should we keep this issue open so that we can circle back to it later some day?
