### ISSUE TITLE
story: review error messages

### ISSUE THREAD

**Issue by clample** [checkly/checkly-cli#555]
### Story description

Follow up for https://github.com/checkly/checkly-cli/pull/553#issuecomment-1443728594

We should 
1. Migrate error messages to a central `messages.ts` file. This can make it easier to keep track of what error message copy we have.
2. Go through all common error cases and make sure that they're covered nicely. Ideally we should give tips on how to solve issues and link to the relevant documentation.

**Comment by tnolet** [comment]
@clample and rest. I think right now adding another layer of indirection to centralize error messages will not be a good use of our time. I will review all messages for correct copy and typos and close this issue.
