### ISSUE TITLE
story: target a specific configuration with `-c` / `--config` flag

### ISSUE THREAD

**Issue by tnolet** [checkly/checkly-cli#577]
### Story description

We want to allow users to manage different target for test, deployment from one code base. The cleanest solution is to let users define different `checkly.config.ts` files that have different settings. This creates a composable way to:

- target different environments like staging, production etc.
- enables even cross account, cross project workflows by appending different credentials to a `npx checkly <command> -c <config>` invocation

## `-c` / `--config` flag

- Flag applies to `test` and `deploy` commands.
- When no flag is set, defaults to `checkly.config.ts` and then `checkly.config.js` in root directory

**Comment by nahuelon** [comment]
@umutuzgur @clample , should we add the flag for the `destroy` command?

**Comment by clample** [comment]
@nahuelon good point. That makes sense to me.
