### ISSUE TITLE
story: move CHECKLY prefixed envs to `AuthCommand` base class so they are documented

### ISSUE THREAD

**Issue by umutuzgur** [checkly/checkly-cli#588]
### Story description

We have 2 special env vars for bypassing the auth flow which we use heavily with the CI use case. We are not using the oclif framework to set this env vars which then causes it not to be printed when a user invokes the `--help` command. Instead, we should move these to the `AuthCommand` so they are documented and easier to be discovered by the user

**Comment by nahuelon** [comment]
I tried to add the env variables to the flags but the `--help` doesn't show any environment variable description. I found someone ask for that feature in https://github.com/oclif/oclif/issues/691

**Comment by tnolet** [comment]
@umutuzgur is this still relevant?

**Comment by umutuzgur** [comment]
@tnolet yeah

**Comment by nahuelon** [comment]
> no, this is an antipattern. We should not have flags to set credentials. You cannot encourage users to visibly set credentials in a command line app which will be logged by CI systems etc. They should always be ENV VARS.

@tnolet , I agree. And, is it OK to keep the flags for the `login`?

**Comment by tnolet** [comment]
> > no, this is an antipattern. We should not have flags to set credentials. You cannot encourage users to visibly set credentials in a command line app which will be logged by CI systems etc. They should always be ENV VARS.
> 
> @tnolet , I agree. And, is it OK to keep the flags for the `login`?

No, no flag at all. Login is interactive. If you don't want interactive, use env vars.

**Comment by nahuelon** [comment]
I created https://github.com/checkly/checklyhq.com/pull/813 to add the `CHECKLY_ACCOUNT_NAME` description to the /docs
