### ISSUE TITLE
feat: `checkly test` to respect `locations` set on groups or checks

### ISSUE THREAD

**Issue by tdeekens** [checkly/checkly-cli#678]
### What problem does this feature solve?

Checks can target environments running around the world. Ideally checks should run close to the actual user group. Otherwise complex browser checks can also time out.

When using the `checkly test` command the checks always run from the default location or from a location passed with `-`l.

When setting up checks the group or check themselves can already have `locations` assigned to them. It might be beneficial to respect them when running the checks also using the CLI and not just from the web application in the end.

### How would you implement this feature?

To have the `-l` value of the CLI respect the checks and group's location if defined.

**Comment by tnolet** [comment]
@tdeekens this behaviour is on purpose. When there is more than one location defined (as is in most cases) we do not know what location to run when you execute "test". For this reason it's parametrized.
