### ISSUE TITLE
feat: add visual indication to checks created via CLI

### ISSUE THREAD

**Issue by tdeekens** [checkly/checkly-cli#690]
### What problem does this feature solve?

Checks can be super easily created using the CLI. Checkly‘s interface however is also easy to use. 

At times users may run into an issue in which a check created via the CLI is edit by another user in the UI. This would cause drift (borrowing the term from Terraform). 

Even though this can be solved with a different project or aborting syncing via the CLI upon drift detection one could tackle the issue in the ui. 

### How would you implement this feature?

Adding visual markers to any entity in the ui created with the CLI could help. 
One could also warn upon save stating that a given entity (group, channel, check) has been managed by the CLI and saving could cause drift. 

It‘s all just an idea you likely have thought about. I just wanted to share what would help me.

**Comment by tdeekens** [comment]
Great stuff @tnolet! Feel free to close this then if you have the work planned and tracked elsewhere 😄.

**Comment by tnolet** [comment]
Okido, will close!
