### ISSUE TITLE
feat: add `--test-session-name` to `test` command

### ISSUE THREAD

**Issue by tdeekens** [checkly/checkly-cli#704]
### What problem does this feature solve?

The `trigger` command has a `--record` option, just like the `test` command. However, only `trigger` seems to have the `--test-session-name` option. While invocation of either command appears in Test Sessions inside the UI.

According to this the command's code [here](https://github.com/checkly/checkly-cli/blob/main/packages/cli/src/commands/trigger.ts#L67-L74) and [here](https://github.com/checkly/checkly-cli/blob/main/packages/cli/src/commands/test.ts#L76-L79) the option might be missing.

### How would you implement this feature?

Add the option to the `test` command so it's added when Checkly's CLI makes the API call. There might be some internal differences in how `trigger` and `test` are implemented which makes this not possible.

**Comment by tnolet** [comment]
@tdeekens when using `test` we derive the project name from the `checkly.config.ts` file. This is the recommended approach. As using `trigger` does not require any `checkly.config.ts` file to exist, we added to option to still name the project so we can show a better Test Overview in the web UI.

Does that make sense

**Comment by tdeekens** [comment]
Thanks. That makes perfect sense. However, when using test one might trigger want a better name to distinguish the those as test sessions in the web UI than the project name. In addition one could target different checks using different invocations of the test command at which time being able to overwrite the test session name could be beneficial. In that the project config's name remains the default but can be overwritten maybe.
