### ISSUE TITLE
bug: Existing alert channels aren't subscribed to checks published through the CLI

### ISSUE THREAD

**Issue by ngarside** [checkly/checkly-cli#722]
### Node.js version

18.16.0

### NPM version

9.5.1

### @checkly/cli version

0.4.13

### Steps to reproduce

- Create an alert channel with 'automatically subscribe newly created checks to this alert channel' enabled
- Publish a new api check through the CLI

### What is expected?

The existing channel will be subscribed to the new check

### What is actually happening?

The existing channel is not subscribed to the new check, nor can it be manually subscribed through the web UI

**Comment by tnolet** [comment]
@ngarside thanks for reporting this. I think this works as designed, but isn't clear enough in how behaviour is different between things you create in the CLI vs. the UI.

- Any alert channel you want to use from a CLI Project needs to be explicitly linked / created. This is on purpose, as a Checkly CLI Project needs to fully define the resources it uses.
- The toggle "automatically subscribe newly created checks..." only works when creating checks via the UI. 

So, there are two things you can do:
- Just set up the alert channel in your CLI codebase and use it through out your checks.
- Keep the alert channel you defined in the UI and use it in your CLI code base using the `.fromId()` notation. Check out the docs on that here. https://www.checklyhq.com/docs/cli/constructs-reference#using-fromid-to-reference-an-existing-channel

**Comment by ngarside** [comment]
Thanks @tnolet https://www.checklyhq.com/docs/cli/constructs-reference#using-fromid-to-reference-an-existing-channel is exactly what I wanted.

> I think this works as designed, but isn't clear enough in how behaviour is different between things you create in the CLI vs. the UI.

Yes, been really enjoying using checkly but the separation between UI/CLI checks could be a little clearer.

**Comment by tnolet** [comment]
> Thanks @tnolet https://www.checklyhq.com/docs/cli/constructs-reference#using-fromid-to-reference-an-existing-channel is exactly what I was looking for.
> 
> > I think this works as designed, but isn't clear enough in how behaviour is different between things you create in the CLI vs. the UI.
> 
> Yes, been really enjoying using checkly but the separation between UI/CLI checks could be a little clearer.

Thanks Nathan, and you are right. We are doing a whole bunch of work in the background to start this process of clearly indicating UI vs. CLI usage.
