### ISSUE TITLE
bug: `npm create checkly` does not recognize existing project

### ISSUE THREAD

**Issue by tnolet** [checkly/checkly-cli#745]
### Node.js version

18

### NPM version

8

### @checkly/cli version

4.0.8

### Steps to reproduce

- Run `npm create checkly` in a folder that already has a `package.json`

### What is expected?

It should recognize that there is a `package.json` and use a different installation branch, prompting the user to set up `checkly` for an existing project.

### What is actually happening?

it does not recognize it and prompts creating a brand new one.

```
-rw-r--r--@ 1 timnolet  staff   239B May 31 17:13 package-lock.json
-rw-r--r--@ 1 timnolet  staff   222B May 31 17:13 package.json
timnolet@MacBook-Pro-van-Tim playwright-multi-step-test % npm create checkly
 checkly  v4.0.8 Build and Run Synthetics That Scale

Hi Tim Nolet! Let's get you started on your monitoring as code journey!

? Where do you want to create your new project? › purple-parrotfish
```

### Any additional comments?

This is 9999% due to wrong usage of `process.cwd()` in https://github.com/checkly/checkly-cli/blob/62891ff0ec3102896b8467ed58159aaf7c353d63/packages/create-cli/src/utils/package.ts#L12

**Comment by nahuelon** [comment]
@tnolet @maxigimenez , I wasn't able to reproduce the issue. I tried it using Linux and Windows:

![image](https://github.com/checkly/checkly-cli/assets/5315705/09c6553f-a7b6-4d51-ab89-c5732390c34b)

![image](https://github.com/checkly/checkly-cli/assets/5315705/25fca761-5d24-45ea-82a7-c20054574881)

**Comment by tnolet** [comment]
@nahuelon I tried on a MacOS / Darwin and it doesn't work for me

**Comment by maxigimenez** [comment]
@nahuelon are you working on a fix for this? Otherwise, ping me and I can help, it might be related to this change https://github.com/checkly/checkly-cli/pull/713, the original version was working fine, but then was reported that in some cases package.json wasn't detected, so move to use `process.cwd`

**Comment by tnolet** [comment]
We seem to happen only on my machine, I started to crowd source some reports with folks with the same config:
- MacOS / Darwin
- Using `fnm` as Node.js version manager.

A simple script to test this is:


- create an simple node project:
`mkdir my-test`
`cd my-test`
`npm init`
`npm i -S axios`

And then install the Checkly CLI using:

`npm create checkly`

It SHOULD prompt you that you already have a package.json and ask you if you want to use the current project. But, on my machine it somehow cannot read the package.json.

**Comment by tnolet** [comment]
This was fixed by using NPM 9 and Nodejs 18.
