### ISSUE TITLE
bug: `npx checkly trigger` runs into `[...] Deprecated in favor of @oclif/core`

### ISSUE THREAD

**Issue by tdeekens** [checkly/checkly-cli#773]
### Node.js version

19

### NPM version

9.6

### @checkly/cli version

4.0.9

### Steps to reproduce

We invoke Checkly via `npx` such as 

```bash
npx checkly trigger \
    --tags staging,deployment, \
    --record \
    --test-session-name="Deployment of API" \
    --reporter=ci
```

Then we run into

```
npm WARN exec The following package was not found and will be installed: checkly@4.0.9
npm WARN deprecated @oclif/screen@3.0.4: Deprecated in favor of @oclif/core
Unable to run checks: "targetTags[0][2]" is not allowed to be empty
```

### What is expected?

Not to run into a deprecation warning.

### What is actually happening?

NPM throws a deprecation warning.

### Any additional comments?

This is happening as of today and has worked before.

**Comment by tnolet** [comment]
@tdeekens thanks for reporting. I can't reproduce this consistently when running a command, but see the deprecation when doing a fresh install. It's a bit of "fight" on our side with some not so well documented deprecations the `oclif` framework is doing between versions. 

Having said that, we will fix this ASAP. Does running the command still work for you, as I see an error `Unable to run checks: "targetTags[0][2]" is not allowed to be empty` which should not be related to the deprecation warning.

**Comment by tnolet** [comment]
> Right now we can't run the command on CI. It basically stops with the deprecation warning.

That sounds like something else might be wrong, a deprecation warning should not stop the command from executing. Are you getting the `Unable to run checks: "targetTags[0][2]" is not allowed to be empty` error?

**Comment by tdeekens** [comment]
Thanks. Let me double check that on the `,`.

**Comment by tdeekens** [comment]
There indeed is the trailing comma. I'll try to fix it and let you know.

**Comment by tnolet** [comment]
> There indeed is the trailing comma. I'll try to fix it and let you know.

Ok, good to hear you are unblocked. We will prep a release were we can align all the `oclif` deps in a better way.

**Comment by tdeekens** [comment]
Thanks for the suggestion. Removing the trailing `,` fixes it for us. Feel free to close this or keep it open.

**Comment by tnolet** [comment]
Thanks @tdeekens. Let's keep it open so we fix the deprecation notices
