### ISSUE TITLE
vercel integration bug: `"code" is not allowed to be empty`

### ISSUE THREAD

**Issue by Snailedlt** [checkly/checkly-cli#823]
I'm not sure if this is the right place to open the issue, but hopefully it can be forwarded to the right people if not.

I get the following error when I try to set up the checkly integration on vercel: `"code" is not allowed to be empty`
![image](https://github.com/checkly/checkly-cli/assets/43886029/692721b3-ccba-4233-9229-e2fb68c2b6a4)
![image](https://github.com/checkly/checkly-cli/assets/43886029/8e97be2b-73d5-45e6-8023-6bad69c2d32d)
![image](https://github.com/checkly/checkly-cli/assets/43886029/82973ed0-d996-4e2f-853f-8aa7ebcd90f3)
![image](https://github.com/checkly/checkly-cli/assets/43886029/5a2e5e7a-d760-45ca-8bca-98c33a2085d9)
![image](https://github.com/checkly/checkly-cli/assets/43886029/ca145493-a4ad-4142-ab58-1c0db0d9c290)

**Comment by tnolet** [comment]
@Snailedlt thanks for reporting! This is not a bug in our CLI, but certainly is in our Vercel integration wizard. We are looking into it!

**Comment by Snailedlt** [comment]
I figured, but couldn't find any repo for the integration (is it closed source?).
Anyways, let me know if you need more info

**Comment by tnolet** [comment]
> I figured, but couldn't find any repo for the integration (is it closed source?). Anyways, let me know if you need more info

@Snailedlt the integration wizard is indeed closed source, as it is part of our webapp. But we found the bug and shipped a fixed. I just tested it on production and I can integrate Vercel with Checkly again. Let me know if this works for you.

**Comment by Snailedlt** [comment]
It works for me too now. Thank you for the quick fix!
Also, please consider making a repository for issue tracking your closed source projects. Would make it easier for us to find where we can report issues :)
