### ISSUE TITLE
bug: giget has issues fetching our tags

### ISSUE THREAD

**Issue by umutuzgur** [checkly/checkly-cli#844]
### Node.js version

18

### NPM version

7

### @checkly/cli version

4.1.0

### Steps to reproduce

use create-cli with a tag that doesn't have the prefix `v`

### What is expected?

It should work with any tag

### What is actually happening?

It is saying it can't find the tag we are trying to find

**Comment by umutuzgur** [comment]
@clample could you take a look at this next week?

**Comment by clample** [comment]
@umutuzgur with 4.4.0 how did you do the release? It looks like we just need to tag without the `v` and we avoid the issue?

![image](https://github.com/checkly/checkly-cli/assets/10483186/51489e1a-e411-435d-9b28-5488b403a8c3)
