### ISSUE TITLE
bug: Can’t use latest TypeScript

### ISSUE THREAD

**Issue by kirkstrobeck** [checkly/checkly-cli#848]
### Node.js version

v18.12.1

### NPM version

8.19.2

### @checkly/cli version

4.1.0

### Steps to reproduce

I believe typescript at 5.2.2 should be sufficient to repro

### What is expected?

Run successfully

### What is actually happening?

npx checkly test
Parsing your project... ⡿
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <5.0.0

YOUR TYPESCRIPT VERSION: 5.2.2

Please only submit bug reports when using the officially supported version.

Parsing your project... !
    Error: Encountered an error parsing check files for [filepath here]

    The following files couldn't be parsed:
    	[filepath here] - DeprecationError: 'originalKeywordKind' has been deprecated since v5.0.0 and can no longer
     be used. Use 'identifierToKeywordKind(identifier)' instead.

### Any additional comments?

1. Please upgrade @typescript-eslint/typescript-estree
2. Allow opting out of eslint checks for test running

**Comment by tdeekens** [comment]
We're encountering the same issue. We've tried to update other parts (e.g. `@tsconfig`s) first but it really seems to be an incompatibility with TypeScript v5.

**Comment by alvarlagerlof** [comment]
Also facing this. Same error.

**Comment by ellisio** [comment]
For now, if you can, you can downgrade to `typescript@~5.1.0`. This seems to be a breaking change in `typescript@^5.2.0`.

**Comment by tdeekens** [comment]
Yes confirmed it's what we did. In earlier versions than 5.2.0 it is a warning. From 5.2.0 it is treated as an error. Once of those instances of TypeScript not following Semantic Versioning again I suppose 😸.

Maybe compiling the CLI with TypeScript v5 would solve the issue. Right now it seems to be on v4.

**Comment by umutuzgur** [comment]
Hi everyone. Sorry for the late reply here. We will tackle this issue next week. The issue seems to be related to `@typescript-eslint/typescript-estree` and typescript 5.2. We wanted to have smarter solution to this as it was still working with 5.1 so we could come up with a solution that is ts version agnostic but it seems like it doesn't anymore with 5.2

**Comment by umutuzgur** [comment]
Hi everyone 👋 

We have a release cooking at the moment. We will make it on Monday given there were some complicated changes with the ts compiler. If you would like to try the pre release, you can try `npm i checkly@0.0.0-pr.857.4cd41ea`. Like I said, we will make the official release on Monday. Have a great weekend!
