### ISSUE TITLE
bug: Cli connection issue connect ECONNREFUSED 127.0.0.1:3000 Ubuntu 22.04.3 LTS

### ISSUE THREAD

**Issue by reinaldomendes** [checkly/checkly-cli#874]
### Node.js version

v18.16.0

### NPM version

9.5.1

### @checkly/cli version

0.4.13

### Steps to reproduce

I don't know what cause this.

My last interation with this project was in May 24.

Today when I'm trying to test and deploy I'm stuck in problem with network.

I tried to login but the same issue happens.
I tried to update, but the same error happens.

### What is expected?

The cli should works.

### What is actually happening?

```bash 
  npx checkly test --env-file=./.env
  
  ›   Warning: @checkly/cli update available from 0.4.13 to 0.4.14.
    Error: Encountered an error connecting to Checkly. Please check that the internet connection is working. connect ECONNREFUSED 127.0.0.1:3000
```

![Screenshot from 2023-10-30 14-01-55](https://github.com/checkly/checkly-cli/assets/725300/d06e3513-ef28-458d-a4ac-283c048c64ba)

![Screenshot from 2023-10-30 14-11-09](https://github.com/checkly/checkly-cli/assets/725300/06ea146a-6733-4702-aad0-eb110986f56c)

### Any additional comments?

I'm running the CLI on Ubuntu 22.04.3 LTS

My package.json
```json
{
  "name": "advanced-project",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "type": "commonjs",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "checkly:deploy": "npx checkly deploy --force",
    "checkly:test": "npx checkly test"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@checkly/cli": "latest",
    "@playwright/test": "^1.33.0",
    "@types/axios": "^0.14.0",
    "@types/btoa": "^1.2.3",
    "@types/crypto-js": "^4.1.1",
    "dotenv": "^16.0.3",
    "ts-node": "10.9.1",
    "typescript": "4.9.5"
  },
  "dependencies": {
    "axios": "^0.27.2",
    "btoa": "^1.2.1",
    "crypto-js": "^4.1.1",
    "date-fns": "^2.29.3",
    "date-fns-tz": "^2.0.0"
  }
}
```

**Comment by clample** [comment]
Hi @reinaldomendes,

Thanks for reporting this issue and sorry for the inconvenience. 

We migrated the project from `@checkly/cli` to `checkly`, and we've changed quite a bit since version `0.4.13`. Could you please try again with the latest version? To migrate from `@checkly/cli` to `checkly`, we have a quick guide in the README here: https://www.npmjs.com/package/@checkly/cli.

If the issue persists, please feel free to ping me and I'll try to help find a solution.

**Comment by tnolet** [comment]
@reinaldomendes can you let us know if the above suggestion fixes your issue?

**Comment by tnolet** [comment]
Closing this issue
