### ISSUE TITLE
bug: Fix proxy auth assignment while creating tunnel agent

### ISSUE THREAD

**Issue by abhimanbhau** [checkly/checkly-cli#967]
### Node.js version

20.16.0

### NPM version

10.8.1

### @checkly/cli version

4.9.0

### Steps to reproduce

Setting up HTTPS_PROXY via environment variable doesn't work as there's a bug in the code while constructing proxy.Auth object.

### What is expected?

Correctly set the username/password from HTTPS_PROXY environment variable.

### What is actually happening?

undefined:undefined is being set

### Any additional comments?

1. https://github.com/checkly/checkly-cli/blob/main/packages/cli/src/services/socket-client.ts#L47
2. https://github.com/checkly/checkly-cli/blob/main/packages/cli/src/services/util.ts#L212

Both cases the issue is the line
```
proxy.proxyAuth = `${proxyUrlEnv.username}:${proxyUrlEnv.password}`
```

proxyUrlEnv is a string object returned from getProxyForUrl method.

Changing the line to 
```
proxy.proxyAuth = `${parsedProxyUrl.username}:${parsedProxyUrl.password}`
```
fixes the issue.

**Comment by maxigimenez** [comment]
@abhimanbhau 4.9.1 version contains your fixes, thanks for the contribution
