### ISSUE TITLE
bug: Webapp: import traces is not working

### ISSUE THREAD

**Issue by sir-alex** [checkly/checkly-cli#998]
### Node.js version

18.18.0

### NPM version

9.8.1

### @checkly/cli version

4.14.0

### Steps to reproduce

Sorry for writing about this bug in this repository as I did not manage to find a repo related to APi specifically or WebApp. As this repo is pinned I will leave this bug here

I was trying to enable traces to check it in my WebApp running on EC2 and was following a video from https://www.checklyhq.com/docs/traces-open-telemetry/
I was not able to switch Import traces slider in my https://app.checklyhq.com/settings/account/traces

In webUi I see this
![image](https://github.com/user-attachments/assets/de434437-c761-433d-9ae5-c52ec5edbd94)

In console I see 
```
Access to XMLHttpRequest at 'https://api.checklyhq.com/accounts/<my account id>' from origin 'https://app.checklyhq.com' has been blocked by CORS policy: Method PATCH is not allowed by Access-Control-Allow-Methods in preflight response.
```
After I switched plugin to ignore CORS in my browser I got PATCH error as per screenshot attached
![image](https://github.com/user-attachments/assets/7d11e682-2170-45ec-ad4e-053500e20ecf)

I tried a direct curl request

```
curl --location --request PATCH 'https://api.checklyhq.com/accounts/<my account id>' \
--header 'Accept: application/json' \
--header 'X-Checkly-Account: <my account id>' \
--header 'Authorization: Bearer <my ip token>' \
--header 'Content-Type: application/json' \
--data '{
    "settings": {
        "useChecklyOtelProvider": true,
        "tracing": true
    }
}'
```
I got 401 error . But other API calls with same headers are working

I tried to call otel API from curl but I got redirection
```
curl -I https://otel.eu-west-1.checklyhq.com/v1/traces
HTTP/2 301 
date: Sun, 08 Dec 2024 17:51:55 GMT
location: https://www.checklyhq.com/docs/traces-open-telemetry
```

My software: 
Brave v1.73.97
Ubuntu 22.04 LTS

### What is expected?

It should work I guess

### What is actually happening?

see above

**Comment by sir-alex** [comment]
I see you monitor bugs with sentry and I guess you can easily track this bug in sentry

**Comment by MariadeAnton** [comment]
Hey @sir-alex! Thank you so much for submitting this bug report, we'll look into it. 

If you'd like to get updates, please ping in our [Slack community](https://www.checklyhq.com/slack/) or email our support team.

In the future, please only report CLI-related issues in this repo. Thank you!

**Comment by sir-alex** [comment]
ok, sorry for wrong repo. I simply did not manage to find the right one. I see problem has been fixed and I can import traces now. Thanks for a fast respond. Appreciated
